# 1: Imports e configurações

In [ ]:
# Manipulação de dados
import pandas as pd
import numpy as np

# Visualização
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

# Machine Learning / Estatística
from sklearn.preprocessing import LabelEncoder
from sklearn.cluster import KMeans

# Configurações visuais
plt.style.use("ggplot")

# Exibir todas as colunas
pd.set_option('display.max_columns', None)

# Exibir números com 2 casas decimais
pd.options.display.float_format = '{:.2f}'.format

# 2: Carregando o arquivo base via GITHUB

In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/elissouza2023/sistema_agua_saneamento/main/data/dados_micromedicao.xls"

# Ler diretamente do GitHub
df = pd.read_excel(url)

print("Planilha carregada com sucesso!")

# Visualizar primeiras linhas
df.head()

Planilha carregada com sucesso!

,MATRICULA,SIT._LIG_AGUA,SIT._LIG_ESGOTO,NUMERO_HIDROMETRO,TIPO_HIDROMETRO,MARCA_HIDROMETRO,CAPACIDADE_HIDROMETRO,DIAMETRO_HIDROMETRO,CLASSE_METROLOGICA,DATA_INSTALACAO_HIDROMETRO,CATEGORIA_PRINCIPAL,NUMERO_ECONOMIAS_RES,NUMERO_ECONOMIAS_COM,NUMERO_ECONOMIAS_IND,NUMERO_ECONOMIAS_PUB,VOLUME_LIDO,VOLUME_REAL,VOLUME_FATURADO,VALOR_AGUA,VALOR_ESGOTO,VALOR_SERVICOS,VALOR_IMPOSTOS,VALOR_DESCONTOS,VALOR_TOTAL,VOLUME_LIDO_01,VOLUME_REAL_01,VOLUME_FATURADO_01,VALOR_AGUA_01,VALOR_ESGOTO_01,VALOR_SERVICOS_01,VALOR_IMPOSTOS_01,VALOR_DESCONTOS_01,VALOR_TOTAL_01,VOLUME_LIDO_02,VOLUME_REAL_02,VOLUME_FATURADO_02,VALOR_AGUA_02,VALOR_ESGOTO_02,VALOR_SERVICOS_02,VALOR_IMPOSTOS_02,VALOR_DESCONTOS_02,VALOR_TOTAL_02,VOLUME_LIDO_03,VOLUME_REAL_03,VOLUME_FATURADO_03,VALOR_AGUA_03,VALOR_ESGOTO_03,VALOR_SERVICOS_03,VALOR_IMPOSTOS_03,VALOR_DESCONTOS_03,VALOR_TOTAL_03,VOLUME_LIDO_04,VOLUME_REAL_04,VOLUME_FATURADO_04,VALOR_AGUA_04,VALOR_ESGOTO_04,VALOR_SERVICOS_04,VALOR_IMPOSTOS_04,VALOR_DESCONTOS_04,VALOR_TOTAL_04,VOLUME_LIDO_05,VOLUME_REAL_05,VOLUME_FATURADO_05,VALOR_AGUA_05,VALOR_ESGOTO_05,VALOR_SERVICOS_05,VALOR_IMPOSTOS_05,VALOR_DESCONTOS_05,VALOR_TOTAL_05,VOLUME_LIDO_06,VOLUME_REAL_06,VOLUME_FATURADO_06,VALOR_AGUA_06,VALOR_ESGOTO_06,VALOR_SERVICOS_06,VALOR_IMPOSTOS_06,VALOR_DESCONTOS_06,VALOR_TOTAL_06,VOLUME_LIDO_07,VOLUME_REAL_07,VOLUME_FATURADO_07,VALOR_AGUA_07,VALOR_ESGOTO_07,VALOR_SERVICOS_07,VALOR_IMPOSTOS_07,VALOR_DESCONTOS_07,VALOR_TOTAL_07,VOLUME_LIDO_08,VOLUME_REAL_08,VOLUME_FATURADO_08,VALOR_AGUA_08,VALOR_ESGOTO_08,VALOR_SERVICOS_08,VALOR_IMPOSTOS_08,VALOR_DESCONTOS_08,VALOR_TOTAL_08,VOLUME_LIDO_09,VOLUME_REAL_09,VOLUME_FATURADO_09,VALOR_AGUA_09,VALOR_ESGOTO_09,VALOR_SERVICOS_09,VALOR_IMPOSTOS_09,VALOR_DESCONTOS_09,VALOR_TOTAL_09,VOLUME_LIDO_10,VOLUME_REAL_10,VOLUME_FATURADO_10,VALOR_AGUA_10,VALOR_ESGOTO_10,VALOR_SERVICOS_10,VALOR_IMPOSTOS_10,VALOR_DESCONTOS_10,VALOR_TOTAL_10,VOLUME_LIDO_11,VOLUME_REAL_11,VOLUME_FATURADO_11,VALOR_AGUA_11,VALOR_ESGOTO_11,VALOR_SERVICOS_11,VALOR_IMPOSTOS_11,VALOR_DESCONTOS_11,VALOR_TOTAL_11,VOLUME_LIDO_12,VOLUME_REAL_12,VOLUME_FATURADO_12,VALOR_AGUA_12,VALOR_ESGOTO_12,VALOR_SERVICOS_12,VALOR_IMPOSTOS_12,VALOR_DESCONTOS_12,VALOR_TOTAL_12
0,1209537-0,Ativa,Ativa,Y22S490239,Unijato,MARCA A,"1,6","3/4""",Classe B,20/02/2024,Residencial,1.00,NaN,NaN,NaN,3.00,3.00,10.00,51.77,41.42,2.74,0.00,0.00,95.93,17.00,17.00,17.00,118.48,94.78,0.00,0.00,0.00,213.26,12.00,12.00,12.00,70.83,56.66,5.16,0.00,0.00,132.65,14.00,14.00,14.00,89.89,71.91,1.81,0.00,0.00,163.61,11.00,11.00,11.00,58.56,46.85,0.00,0.00,0.00,105.41,10.00,10.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03,12.00,12.00,12.00,67.66,54.13,0.00,0.00,0.00,121.79,8.00,8.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03,10.00,10.00,10.00,49.46,39.57,1.85,0.00,0.00,90.88,10.00,10.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03,10.00,10.00,10.00,49.46,39.57,1.90,0.00,0.00,90.93,9.00,9.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03,8.00,8.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03
1,1209552-4,Ativa,Ativa,Y21S226374,Unijato,MARCA A,"1,6","3/4""",Classe B,19/10/2021,Residencial,1.00,NaN,NaN,NaN,6.00,6.00,10.00,51.77,41.42,0.00,0.00,0.00,93.19,5.00,5.00,10.00,51.77,41.42,2.94,0.00,0.00,96.13,6.00,6.00,10.00,51.77,41.42,0.00,0.00,0.00,93.19,2.00,2.00,10.00,51.77,41.42,63.68,0.00,0.00,156.87,5.00,5.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03,6.00,6.00,10.00,49.46,39.57,80.10,0.00,0.00,169.13,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN
2,1210192-3,Ativa,Ativa,A21AA0175469,Multijato,MARCA A,"1,5","3/4""",Classe B,14/05/2024,Residencial,1.00,NaN,NaN,NaN,21.00,21.00,21.00,156.60,125.28,0.00,0.00,0.00,281.88,28.00,28.00,28.00,234.44,187.55,0.00,0.00,0.00,421.99,34.00,34.00,34.00,313.88,251.10,0.00,0.00,0.00,564.98,29.00,29.00,29.00,247.68,198.14,0.00,0.00,0.00,445.82,28.00,28.00,28.00,223.91,179.13,0.00,0.00,0.00,403.04,29.00,29.00,29.00,236.56,189.25,0.00,0.00,0.00,425.81,26.00,26.00,26.00,198.61,158.89,0.00,0.00,0.00,357.50,34.00,34.00,34.00,299.81,239.85,0.00,0.00,0.00,539.66,34.00,34.00,34.00,299.81,239.85,0.00,0.00,0.00,539.66,27.00,27.00,27.00,211.26,169.01,0.00,0.00,0.00,380.27,32.00,32.00,32.00,274.51,219.61,0.00,0.00,0.00,494.12,26.00,26.00,26.00,198.61,158.89,0.00,0.00,0.00,357.50,28.00,28.00,28.00,223.91,179.13,0.00,0.00,0.00,403.04
3,1210205-9,Ativa,Ativa,A23AA0210661,Multijato,MARCA A,"1,5","3/4""",Classe B,21/02/2024,Residencial,1.00,NaN,NaN,NaN,30.00,30.00,30.00,260.92,208.74,0.00,0.00,0.00,469.66,20.00,20.00,20.00,147.07,117.66,15.59,0.00,0.00,280.32,26.00,26.00,26.00,207.96,166.37,0.00,0.00,0.00,374.33,35.00,35.00,35.00,327.12,261.70,0.00,0.00,0.00,588.82,22.00,22.00,22.00,158.66,126.93,168.83,0.00,0.00,454.42,27.00,27.00,27.00,211.26,169.01,0.00,0.00,0.00,380.27,32.00,32.00,32.00,274.51,219.61,0.00,0.00,0.00,494.12,28.00,28.00,28.00,223.91,179.13,0.00,0.00,0.00,403.04,25.00,25.00,25.00,185.96,148.77,0.00,0.00,0.00,334.73,17.00,17.00,17.00,113.16,90.53,34.57,0.00,0.00,238.26,19.00,19.00,19.00,131.36,105.09,35.33,0.00,0.00,271.78,31.00,31.00,31.00,261.86,209.49,0.00,0.00,0.00,471.35,26.00,26.00,26.00,198.61,158.89,0.00,0.00,0.00,357.50
4,1210231-8,Ativa,Ativa,A16B069097,ULTRASSÔNICO,MARCA B,"1,5","3/4""",Classe C,07/03/2017,Residencial,30.00,NaN,NaN,NaN,206.00,206.00,300.00,1553.10,1242.48,0.00,0.00,0.00,2795.58,213.00,213.00,300.00,1553.10,1242.48,0.00,0.00,0.00,2795.58,217.00,217.00,300.00,1553.10,1242.48,0.00,0.00,0.00,2795.58,280.00,280.00,300.00,1553.10,1242.48,0.00,0.00,0.00,2795.58,188.00,188.00,300.00,1483.80,1187.04,0.00,0.00,0.00,2670.84,191.00,191.00,300.00,1483.80,1187.04,0.00,0.00,0.00,2670.84,238.00,238.00,300.00,1483.80,1187.04,0.00,0.00,0.00,2670.84,169.00,169.00,300.00,1483.80,1187.04,0.00,0.00,0.00,2670.84,136.00,136.00,300.00,1483.80,1187.04,0.00,0.00,0.00,2670.84,115.00,115.00,300.00,1483.80,1187.04,0.00,0.00,0.00,2670.84,114.00,114.00,300.00,1483.80,1187.04,0.00,0.00,0.00,2670.84,153.00,153.00,400.00,1978.40,1582.72,0.00,0.00,0.00,3561.12,159.00,159.00,400.00,1978.40,1582.72,0.00,0.00,0.00,3561.12

# 3: Conhecendo a base

In [ ]:
# Informações da base
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1912 entries, 0 to 1911
Columns: 132 entries, MATRICULA to VALOR_TOTAL_12
dtypes: float64(121), object(11)
memory usage: 1.9+ MB

In [ ]:
df.describe()

,NUMERO_ECONOMIAS_RES,NUMERO_ECONOMIAS_COM,NUMERO_ECONOMIAS_IND,NUMERO_ECONOMIAS_PUB,VOLUME_LIDO,VOLUME_REAL,VOLUME_FATURADO,VALOR_AGUA,VALOR_ESGOTO,VALOR_SERVICOS,VALOR_IMPOSTOS,VALOR_DESCONTOS,VALOR_TOTAL,VOLUME_LIDO_01,VOLUME_REAL_01,VOLUME_FATURADO_01,VALOR_AGUA_01,VALOR_ESGOTO_01,VALOR_SERVICOS_01,VALOR_IMPOSTOS_01,VALOR_DESCONTOS_01,VALOR_TOTAL_01,VOLUME_LIDO_02,VOLUME_REAL_02,VOLUME_FATURADO_02,VALOR_AGUA_02,VALOR_ESGOTO_02,VALOR_SERVICOS_02,VALOR_IMPOSTOS_02,VALOR_DESCONTOS_02,VALOR_TOTAL_02,VOLUME_LIDO_03,VOLUME_REAL_03,VOLUME_FATURADO_03,VALOR_AGUA_03,VALOR_ESGOTO_03,VALOR_SERVICOS_03,VALOR_IMPOSTOS_03,VALOR_DESCONTOS_03,VALOR_TOTAL_03,VOLUME_LIDO_04,VOLUME_REAL_04,VOLUME_FATURADO_04,VALOR_AGUA_04,VALOR_ESGOTO_04,VALOR_SERVICOS_04,VALOR_IMPOSTOS_04,VALOR_DESCONTOS_04,VALOR_TOTAL_04,VOLUME_LIDO_05,VOLUME_REAL_05,VOLUME_FATURADO_05,VALOR_AGUA_05,VALOR_ESGOTO_05,VALOR_SERVICOS_05,VALOR_IMPOSTOS_05,VALOR_DESCONTOS_05,VALOR_TOTAL_05,VOLUME_LIDO_06,VOLUME_REAL_06,VOLUME_FATURADO_06,VALOR_AGUA_06,VALOR_ESGOTO_06,VALOR_SERVICOS_06,VALOR_IMPOSTOS_06,VALOR_DESCONTOS_06,VALOR_TOTAL_06,VOLUME_LIDO_07,VOLUME_REAL_07,VOLUME_FATURADO_07,VALOR_AGUA_07,VALOR_ESGOTO_07,VALOR_SERVICOS_07,VALOR_IMPOSTOS_07,VALOR_DESCONTOS_07,VALOR_TOTAL_07,VOLUME_LIDO_08,VOLUME_REAL_08,VOLUME_FATURADO_08,VALOR_AGUA_08,VALOR_ESGOTO_08,VALOR_SERVICOS_08,VALOR_IMPOSTOS_08,VALOR_DESCONTOS_08,VALOR_TOTAL_08,VOLUME_LIDO_09,VOLUME_REAL_09,VOLUME_FATURADO_09,VALOR_AGUA_09,VALOR_ESGOTO_09,VALOR_SERVICOS_09,VALOR_IMPOSTOS_09,VALOR_DESCONTOS_09,VALOR_TOTAL_09,VOLUME_LIDO_10,VOLUME_REAL_10,VOLUME_FATURADO_10,VALOR_AGUA_10,VALOR_ESGOTO_10,VALOR_SERVICOS_10,VALOR_IMPOSTOS_10,VALOR_DESCONTOS_10,VALOR_TOTAL_10,VOLUME_LIDO_11,VOLUME_REAL_11,VOLUME_FATURADO_11,VALOR_AGUA_11,VALOR_ESGOTO_11,VALOR_SERVICOS_11,VALOR_IMPOSTOS_11,VALOR_DESCONTOS_11,VALOR_TOTAL_11,VOLUME_LIDO_12,VOLUME_REAL_12,VOLUME_FATURADO_12,VALOR_AGUA_12,VALOR_ESGOTO_12,VALOR_SERVICOS_12,VALOR_IMPOSTOS_12,VALOR_DESCONTOS_12,VALOR_TOTAL_12
count,1665.00,157.00,83.00,5.00,1829.00,1829.00,1829.00,1815.00,1815.00,1815.00,1815.00,1815.00,1815.00,1815.00,1815.00,1815.00,1800.00,1800.00,1800.00,1800.00,1800.00,1800.00,1810.00,1810.00,1810.00,1798.00,1798.00,1798.00,1798.00,1798.00,1798.00,1803.00,1803.00,1803.00,1791.00,1791.00,1791.00,1791.00,1791.00,1791.00,1801.00,1801.00,1801.00,1794.00,1794.00,1794.00,1794.00,1794.00,1794.00,1796.00,1796.00,1796.00,1782.00,1782.00,1782.00,1782.00,1782.00,1782.00,1791.00,1791.00,1791.00,1781.00,1781.00,1781.00,1781.00,1781.00,1781.00,1783.00,1783.00,1783.00,1771.00,1771.00,1771.00,1771.00,1771.00,1771.00,1772.00,1772.00,1772.00,1757.00,1757.00,1757.00,1757.00,1757.00,1757.00,1761.00,1761.00,1761.00,1748.00,1748.00,1748.00,1748.00,1748.00,1748.00,1761.00,1761.00,1761.00,1745.00,1745.00,1745.00,1745.00,1745.00,1745.00,1755.00,1755.00,1755.00,1742.00,1742.00,1742.00,1742.00,1742.00,1742.00,1748.00,1748.00,1748.00,1735.00,1735.00,1735.00,1735.00,1735.00,1735.00
mean,2.72,4.64,1.01,1.00,5451.77,40.68,45.81,354.48,283.14,9.76,0.03,1.86,645.49,2236.17,33.11,40.35,290.75,232.18,3.80,0.02,2.03,524.68,6672.60,34.73,41.92,306.99,245.82,4.30,0.09,3.79,553.23,2256.14,36.68,43.92,331.09,264.80,-0.85,0.07,1.76,593.20,2825.39,35.40,41.53,289.77,231.31,7.99,0.00,8.21,520.86,2819.97,36.15,41.60,288.93,230.84,-2.18,0.02,1.56,516.01,2781.11,38.22,43.90,316.81,253.51,-2.98,0.05,2.77,564.52,2846.59,36.60,41.73,293.60,234.62,-1.27,0.02,1.13,525.81,1744.49,42.35,47.51,387.20,309.59,-161.01,0.03,1.64,534.11,4593.00,35.38,40.30,281.82,225.22,4.22,0.02,2.52,508.72,19890.79,35.94,40.90,289.05,230.74,1.56,0.03,2.88,518.43,1812.64,36.18,41.65,297.06,236.75,-1.44,0.03,4.09,528.26,4683.92,35.35,41.35,293.51,233.84,0.48,0.02,1.48,526.33
std,10.25,23.60,0.11,0.00,72976.01,132.98,152.56,1135.62,908.65,230.58,1.10,27.83,2031.88,46855.80,111.59,139.33,961.91,769.63,211.96,0.69,28.47,1718.06,81138.61,117.05,144.41,1043.18,835.35,213.69,3.72,63.04,1866.40,46955.37,121.63,148.51,1066.57,853.80,213.16,2.96,27.06,1888.45,52607.02,128.93,146.04,995.32,796.37,188.16,0.13,253.64,1741.44,52604.74,137.25,152.87,1048.77,839.10,292.30,0.85,21.18,1753.06,51805.80,133.40,153.93,1079.24,863.63,276.48,2.16,53.09,1891.74,52829.51,132.23,146.22,989.56,791.73,248.60,0.89,17.26,1732.07,41122.03,269.71,276.68,3838.49,3070.82,6689.80,1.26,20.52,1738.37,67255.71,126.78,140.36,953.69,763.05,342.49,1.01,43.58,1673.18,139425.79,129.37,142.92,1000.55,800.64,371.28,1.39,60.13,1710.92,41302.74,126.85,147.44,1026.24,821.22,320.49,1.14,101.37,1797.97,67540.02,121.67,145.22,1023.08,818.62,319.28,0.95,21.48,1786.31
min,1.00,1.00,1.00,1.00,0.00,0.00,0.00,0.00,0.00,-7019.68,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,-4707.72,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,-4843.82,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,-4482.22,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,-5640.95,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,-7176.31,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,-6006.44,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,-5711.69,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,-280240.43,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,-8436.93,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,-13505.58,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,-7604.15,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,-7254.28,0.00,0.00,0.00
25%,1.00,1.00,1.00,1.00,10.00,10.00,10.00,61.30,49.04,0.00,0.00,0.00,127.49,8.00,8.00,10.00,51.77,41.42,0.00,0.00,0.00,97.53,9.00,9.00,10.00,51.77,41.42,0.00,0.00,0.00,99.58,9.00,9.00,10.00,61.30,49.04,0.00,0.00,0.00,127.49,9.00,9.00,10.00,49.46,39.57,0.00,0.00,0.00,95.02,9.00,9.00,10.00,49.46,39.57,0.00,0.00,0.00,93.34,9.00,9.00,10.00,58.56,46.85,0.00,0.00,0.00,105.41,9.00,9.00,10.00,58.56,39.57,0.00,0.00,0.00,105.41,9.00,9.00,10.00,49.46,39.57,0.00,0.00,0.00,105.41,8.00,8.00,10.00,49.46,39.57,0.00,0.00,0.00,94.30,9.00,9.00,10.00,49.46,39.57,0.00,0.00,0.00,96.31,8.00,8.00,10.00,49.46,39.57,0.00,0.00,0.00,95.14,9.00,9.00,10.00,49.46,39.57,0.00,0.00,0.00,105.41
50%,1.00,1.00,1.00,1.00,17.00,17.00,17.00,128.01,102.41,0.00,0.00,0.00,242.30,14.00,14.00,14.00,89.89,71.91,0.00,0.00,0.00,183.40,15.00,15.00,15.00,99.42,79.54,0.00,0.00,0.00,203.96,17.00,17.00,17.00,118.48,94.78,0.00,0.00,0.00,232.37,15.00,15.00,15.00,94.96,75.97,0.00,0.00,0.00,187.31,15.00,15.00,15.00,94.96,75.97,0.00,0.00,0.00,190.00,16.00,16.00,16.00,104.06,83.25,0.00,0.00,0.00,219.47,16.00,16.00,16.00,104.06,83.25,0.00,0.00,0.00,203.69,16.00,16.00,16.00,104.06,83.25,0.00,0.00,0.00,203.69,14.00,14.00,14.00,94.96,75.97,0.00,0.00,0.00,187.31,15.00,15.00,15.00,94.96,75.97,0.00,0.00,0.00,190.36,15.00,15.00,15.00,94.96,75.97,0.00,0.00,0.00,190.16,16.00,16.00,16.00,104.06,83.25,0.00,0.00,0.00,203.69
75%,1.00,1.00,1.00,1.00,27.00,27.00,27.00,221.20,176.96,2.81,0.00,0.00,427.57,22.00,22.00,22.00,166.13,132.90,2.36,0.00,0.00,324.65,24.75,24.00,24.00,194.72,155.78,3.31,0.00,0.00,374.33,27.00,27.00,27.00,221.20,176.96,3.19,0.00,0.00,421.99,23.00,23.00,23.00,167.76,134.21,3.29,0.00,0.00,334.73,23.00,23.00,23.00,167.76,134.21,2.90,0.00,0.00,324.88,26.00,26.00,26.00,198.61,158.89,3.84,0.00,0.00,382.50,25.00,25.00,25.00,190.78,152.62,3.08,0.00,0.00,367.81,25.00,24.00,25.00,185.96,148.77,3.45,0.00,0.00,357.50,22.00,22.00,22.00,167.76,134.21,4.79,0.00,0.00,334.73,24.00,23.00,23.00,176.86,141.49,4.50,0.00,0.00,343.40,23.00,23.00,23.00,176.86,141.49,3.29,0.00,0.00,334.73,24.00,24.00,24.00,185.96,148.77,3.81,0.00,0.00,357.50
max,193.00,213.00,2.00,1.00,999422.00,3091.00,3091.00,21016.26,16813.01,1257.15,46.81,660.31,37829.27,999999.00,2913.00,2913.00,19297.44,15437.95,1257.15,29.09,706.48,34735.39,999999.00,2887.00,2887.00,19049.66,15239.73,1281.36,157.84,1712.41,34289.39,999998.00,3230.00,3230.00,22363.41,17890.73,758.72,125.18,816.54,39016.32,999997.00,2963.00,2963.00,18887.20,15109.76,1310.49,5.51,10683.36,33996.96,999995.00,3665.00,3665.00,25361.48,20289.18,565.97,35.81,493.07,38474.35,999996.00,3557.00,3557.00,24357.16,19485.72,565.97,91.07,1950.00,43842.88,1000047.00,3123.00,3123.00,20364.72,16291.77,720.77,37.61,450.43,36656.49,999997.00,9982.00,9982.00,155838.69,124670.95,720.76,52.75,400.81,35853.87,1000018.00,2877.00,2877.00,18104.60,14483.68,5108.35,42.05,1563.98,32588.28,1000639.00,2992.00,2992.00,19151.10,15320.88,720.76,58.10,2185.87,34471.98,999999.00,3258.00,3258.00,21614.74,17291.79,720.76,47.69,4021.74,38906.53,999998.00,3216.00,3216.00,21232.54,16986.03,5048.49,39.72,559.47,38218.57

In [ ]:
#Rótulos de colunas
df.columns.tolist()

['MATRICULA',
 'SIT._LIG_AGUA',
 'SIT._LIG_ESGOTO',
 'NUMERO_HIDROMETRO',
 'TIPO_HIDROMETRO',
 'MARCA_HIDROMETRO',
 'CAPACIDADE_HIDROMETRO',
 'DIAMETRO_HIDROMETRO',
 'CLASSE_METROLOGICA',
 'DATA_INSTALACAO_HIDROMETRO',
 'CATEGORIA_PRINCIPAL',
 'NUMERO_ECONOMIAS_RES',
 'NUMERO_ECONOMIAS_COM',
 'NUMERO_ECONOMIAS_IND',
 'NUMERO_ECONOMIAS_PUB',
 'VOLUME_LIDO',
 'VOLUME_REAL',
 'VOLUME_FATURADO',
 'VALOR_AGUA',
 'VALOR_ESGOTO',
 'VALOR_SERVICOS',
 'VALOR_IMPOSTOS',
 'VALOR_DESCONTOS',
 'VALOR_TOTAL',
 'VOLUME_LIDO_01',
 'VOLUME_REAL_01',
 'VOLUME_FATURADO_01',
 'VALOR_AGUA_01',
 'VALOR_ESGOTO_01',
 'VALOR_SERVICOS_01',
 'VALOR_IMPOSTOS_01',
 'VALOR_DESCONTOS_01',
 'VALOR_TOTAL_01',
 'VOLUME_LIDO_02',
 'VOLUME_REAL_02',
 'VOLUME_FATURADO_02',
 'VALOR_AGUA_02',
 'VALOR_ESGOTO_02',
 'VALOR_SERVICOS_02',
 'VALOR_IMPOSTOS_02',
 'VALOR_DESCONTOS_02',
 'VALOR_TOTAL_02',
 'VOLUME_LIDO_03',
 'VOLUME_REAL_03',
 'VOLUME_FATURADO_03',
 'VALOR_AGUA_03',
 'VALOR_ESGOTO_03',
 'VALOR_SERVICOS_03',
 'VALOR_IMPOSTOS_03',
 'VALOR_DESCONTOS_03',
 'VALOR_TOTAL_03',
 'VOLUME_LIDO_04',
 'VOLUME_REAL_04',
 'VOLUME_FATURADO_04',
 'VALOR_AGUA_04',
 'VALOR_ESGOTO_04',
 'VALOR_SERVICOS_04',
 'VALOR_IMPOSTOS_04',
 'VALOR_DESCONTOS_04',
 'VALOR_TOTAL_04',
 'VOLUME_LIDO_05',
 'VOLUME_REAL_05',
 'VOLUME_FATURADO_05',
 'VALOR_AGUA_05',
 'VALOR_ESGOTO_05',
 'VALOR_SERVICOS_05',
 'VALOR_IMPOSTOS_05',
 'VALOR_DESCONTOS_05',
 'VALOR_TOTAL_05',
 'VOLUME_LIDO_06',
 'VOLUME_REAL_06',
 'VOLUME_FATURADO_06',
 'VALOR_AGUA_06',
 'VALOR_ESGOTO_06',
 'VALOR_SERVICOS_06',
 'VALOR_IMPOSTOS_06',
 'VALOR_DESCONTOS_06',
 'VALOR_TOTAL_06',
 'VOLUME_LIDO_07',
 'VOLUME_REAL_07',
 'VOLUME_FATURADO_07',
 'VALOR_AGUA_07',
 'VALOR_ESGOTO_07',
 'VALOR_SERVICOS_07',
 'VALOR_IMPOSTOS_07',
 'VALOR_DESCONTOS_07',
 'VALOR_TOTAL_07',
 'VOLUME_LIDO_08',
 'VOLUME_REAL_08',
 'VOLUME_FATURADO_08',
 'VALOR_AGUA_08',
 'VALOR_ESGOTO_08',
 'VALOR_SERVICOS_08',
 'VALOR_IMPOSTOS_08',
 'VALOR_DESCONTOS_08',
 'VALOR_TOTAL_08',
 'VOLUME_LIDO_09',
 'VOLUME_REAL_09',
 'VOLUME_FATURADO_09',
 'VALOR_AGUA_09',
 'VALOR_ESGOTO_09',
 'VALOR_SERVICOS_09',
 'VALOR_IMPOSTOS_09',
 'VALOR_DESCONTOS_09',
 'VALOR_TOTAL_09',
 'VOLUME_LIDO_10',
 'VOLUME_REAL_10',
 'VOLUME_FATURADO_10',
 'VALOR_AGUA_10',
 'VALOR_ESGOTO_10',
 'VALOR_SERVICOS_10',
 'VALOR_IMPOSTOS_10',
 'VALOR_DESCONTOS_10',
 'VALOR_TOTAL_10',
 'VOLUME_LIDO_11',
 'VOLUME_REAL_11',
 'VOLUME_FATURADO_11',
 'VALOR_AGUA_11',
 'VALOR_ESGOTO_11',
 'VALOR_SERVICOS_11',
 'VALOR_IMPOSTOS_11',
 'VALOR_DESCONTOS_11',
 'VALOR_TOTAL_11',
 'VOLUME_LIDO_12',
 'VOLUME_REAL_12',
 'VOLUME_FATURADO_12',
 'VALOR_AGUA_12',
 'VALOR_ESGOTO_12',
 'VALOR_SERVICOS_12',
 'VALOR_IMPOSTOS_12',
 'VALOR_DESCONTOS_12',
 'VALOR_TOTAL_12']

In [ ]:
#Padronização das colunas, todas com letras minusculas, sem espaços, substituido Ç por c e Ã para A
df.columns = (
    df.columns
    .str.strip()
    .str.upper()
    .str.replace(' ', '_')
    .str.replace('Ç', 'C')
    .str.replace('Ã', 'A')
)

In [ ]:
# Verificando colunas vazias
df.isnull().sum()

MATRICULA               0
SIT._LIG_AGUA          15
SIT._LIG_ESGOTO        36
NUMERO_HIDROMETRO      82
TIPO_HIDROMETRO        82
                     ...
VALOR_ESGOTO_12       177
VALOR_SERVICOS_12     177
VALOR_IMPOSTOS_12     177
VALOR_DESCONTOS_12    177
VALOR_TOTAL_12        177
Length: 132, dtype: int64

# 4: Salvando o DataFrame

In [13]:
# Exportando a base tratada para csv

df.to_csv(
    'dados_tratados.csv',
    index=False,
    encoding='utf-8'
)

print("CSV salvo com sucesso!")

CSV salvo com sucesso!

# 5: Criando gráficos comparativos